### PR TITLE
Use GIT_DIR as favorable script working directory.

### PR DESCRIPTION
**Pull request by jodator**
There is a problem with running guppy from other environment then CLI.
Error given in PHPStorm when running it's git commit: "Commit failed with error: [13:25:54] No gulpfile found".

This is due the fact the PHPStorm's tool runs with different PWD then when running from command line: https://youtrack.jetbrains.com/issue/WI-30849.

As proposed in jetbrains tracker using a GIT_DIR is better.

### CODE REVIEW

**Comment by jodator** [comment]
Hi @therealklanni, any chance that you could look at it?

**Comment by therealklanni** [comment]
I don't think adding code specific to an IDE is a great idea. Usually this is resolved by having the `PATH` properly set. Can you try setting `PATH` so `git` is found?

**Comment by jodator** [comment]
The thing is that git (program) is working here (git is in `PATH`).
The problem is with working directory of the process that runs git command (ie. commit) that then executes hook.
While using command line it works flawless but when the git is run differently then this problems occurs.

As pointed out using `GIT_DIR` is more reliable then process working dir (PWD) so this change.

> It's recommended to use environment variable GIT_DIR because current directory may be very different depending on current context.

Also proposed change is not IDE specific but rather GIT specific an works in both scenarios (CLI and int this case PHPStorm IDE).

**Comment by therealklanni** [comment]
I believe there are some packages that determine the app root, such as [node-app-root-path](https://github.com/inxilpro/node-app-root-path). If you want to submit a PR using this package (or if you find one you think is better in some way) in place of `pwd`, I would very much appreciate your contribution. I think this would be a better approach than having an env var to control it.

**Comment by jodator** [comment]
Switched to `husky` as it supports better different workflows.

**Pull request closed without merging**
